name: CI

on:
  push:
    branches:
      - '**'  # Triggers on any branch
  pull_request:
    branches:
      - '**'  # Triggers on pull requests to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Linting
      run: |
        # Install flake8
        pip install flake8
        # Run flake8
        flake8 . --ignore=E501,F401,F403,F405,W504

    - name: Run tests
      run: |
        poetry run pytest tests/  # Adjust the path to your test directory